config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: mongo_etl
      host: 18.140.112.89
      pass: bvxJaDGW2R55uyDXfODJ2a0Y
      port: 5432
      schema: public
      threads: 8
      type: postgres
      user: selly
  target: prod
