config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: selly_etl
      host: localhost
      pass: '123'
      port: 5555
      schema: public
      threads: 8
      type: postgres
      user: selly
  target: prod
