version: 2
sources:
- name: unibag
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_cities
  - name: _airbyte_raw_districts
  - name: _airbyte_raw_wards
